keycloak:
  custom:
    admin-user:
      password: admin
  profile:
    feature:
      scripts: enabled
      upload_scripts: enabled
spring:
  jpa:
    open-in-view: false
#  mvc:
#    servlet:
#      path: /auth-ext

